# Generated by Django 4.2.7 on 2023-12-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='category',
        ),
    ]
