# Generated by Django 4.2.7 on 2023-12-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0003_rename_categoryname_categorymodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='name',
            new_name='CategoryName',
        ),
    ]
